services:
  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    network_mode: host
    env_file:
      - ./backend/.env
    restart: always
    # REMOVE `ports:` and `networks:` when using network_mode: host

networks:
  app-network:
